// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package protobuf;

public final class PacketProtos {
  private PacketProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * UUID of client/server sending the message
     * Server username is SERVER
     * </pre>
     *
     * <code>string UUID = 1;</code>
     */
    java.lang.String getUUID();
    /**
     * <pre>
     * UUID of client/server sending the message
     * Server username is SERVER
     * </pre>
     *
     * <code>string UUID = 1;</code>
     */
    com.google.protobuf.ByteString
        getUUIDBytes();

    /**
     * <code>.protobuf.Packet.Type type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>.protobuf.Packet.Type type = 2;</code>
     */
    protobuf.PacketProtos.Packet.Type getType();

    /**
     * <pre>
     * Message contents
     * </pre>
     *
     * <code>repeated string message = 3;</code>
     */
    java.util.List<java.lang.String>
        getMessageList();
    /**
     * <pre>
     * Message contents
     * </pre>
     *
     * <code>repeated string message = 3;</code>
     */
    int getMessageCount();
    /**
     * <pre>
     * Message contents
     * </pre>
     *
     * <code>repeated string message = 3;</code>
     */
    java.lang.String getMessage(int index);
    /**
     * <pre>
     * Message contents
     * </pre>
     *
     * <code>repeated string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes(int index);

    /**
     * <pre>
     * Additional info used for some Packet types
     * </pre>
     *
     * <code>repeated string addon = 4;</code>
     */
    java.util.List<java.lang.String>
        getAddonList();
    /**
     * <pre>
     * Additional info used for some Packet types
     * </pre>
     *
     * <code>repeated string addon = 4;</code>
     */
    int getAddonCount();
    /**
     * <pre>
     * Additional info used for some Packet types
     * </pre>
     *
     * <code>repeated string addon = 4;</code>
     */
    java.lang.String getAddon(int index);
    /**
     * <pre>
     * Additional info used for some Packet types
     * </pre>
     *
     * <code>repeated string addon = 4;</code>
     */
    com.google.protobuf.ByteString
        getAddonBytes(int index);
  }
  /**
   * Protobuf type {@code protobuf.Packet}
   */
  public  static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      uUID_ = "";
      type_ = 0;
      message_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      addon_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uUID_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                message_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              message_.add(s);
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                addon_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              addon_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          message_ = message_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          addon_ = addon_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.PacketProtos.internal_static_protobuf_Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.PacketProtos.internal_static_protobuf_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.PacketProtos.Packet.class, protobuf.PacketProtos.Packet.Builder.class);
    }

    /**
     * <pre>
     * A command enum that determines how this message will be parsed
     * </pre>
     *
     * Protobuf enum {@code protobuf.Packet.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CONNECTION = 0;</code>
       */
      CONNECTION(0),
      /**
       * <code>LOBBY = 1;</code>
       */
      LOBBY(1),
      /**
       * <code>START_GAME = 2;</code>
       */
      START_GAME(2),
      /**
       * <code>PLAY_CARD = 3;</code>
       */
      PLAY_CARD(3),
      /**
       * <code>BUY_CARD = 4;</code>
       */
      BUY_CARD(4),
      /**
       * <code>GAIN_CARD = 5;</code>
       */
      GAIN_CARD(5),
      /**
       * <code>DRAW_CARD = 6;</code>
       */
      DRAW_CARD(6),
      /**
       * <code>END_TURN = 7;</code>
       */
      END_TURN(7),
      /**
       * <code>END_GAME = 8;</code>
       */
      END_GAME(8),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>CONNECTION = 0;</code>
       */
      public static final int CONNECTION_VALUE = 0;
      /**
       * <code>LOBBY = 1;</code>
       */
      public static final int LOBBY_VALUE = 1;
      /**
       * <code>START_GAME = 2;</code>
       */
      public static final int START_GAME_VALUE = 2;
      /**
       * <code>PLAY_CARD = 3;</code>
       */
      public static final int PLAY_CARD_VALUE = 3;
      /**
       * <code>BUY_CARD = 4;</code>
       */
      public static final int BUY_CARD_VALUE = 4;
      /**
       * <code>GAIN_CARD = 5;</code>
       */
      public static final int GAIN_CARD_VALUE = 5;
      /**
       * <code>DRAW_CARD = 6;</code>
       */
      public static final int DRAW_CARD_VALUE = 6;
      /**
       * <code>END_TURN = 7;</code>
       */
      public static final int END_TURN_VALUE = 7;
      /**
       * <code>END_GAME = 8;</code>
       */
      public static final int END_GAME_VALUE = 8;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return CONNECTION;
          case 1: return LOBBY;
          case 2: return START_GAME;
          case 3: return PLAY_CARD;
          case 4: return BUY_CARD;
          case 5: return GAIN_CARD;
          case 6: return DRAW_CARD;
          case 7: return END_TURN;
          case 8: return END_GAME;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protobuf.PacketProtos.Packet.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.Packet.Type)
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uUID_;
    /**
     * <pre>
     * UUID of client/server sending the message
     * Server username is SERVER
     * </pre>
     *
     * <code>string UUID = 1;</code>
     */
    public java.lang.String getUUID() {
      java.lang.Object ref = uUID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uUID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * UUID of client/server sending the message
     * Server username is SERVER
     * </pre>
     *
     * <code>string UUID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUUIDBytes() {
      java.lang.Object ref = uUID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.protobuf.Packet.Type type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.protobuf.Packet.Type type = 2;</code>
     */
    public protobuf.PacketProtos.Packet.Type getType() {
      @SuppressWarnings("deprecation")
      protobuf.PacketProtos.Packet.Type result = protobuf.PacketProtos.Packet.Type.valueOf(type_);
      return result == null ? protobuf.PacketProtos.Packet.Type.UNRECOGNIZED : result;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList message_;
    /**
     * <pre>
     * Message contents
     * </pre>
     *
     * <code>repeated string message = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMessageList() {
      return message_;
    }
    /**
     * <pre>
     * Message contents
     * </pre>
     *
     * <code>repeated string message = 3;</code>
     */
    public int getMessageCount() {
      return message_.size();
    }
    /**
     * <pre>
     * Message contents
     * </pre>
     *
     * <code>repeated string message = 3;</code>
     */
    public java.lang.String getMessage(int index) {
      return message_.get(index);
    }
    /**
     * <pre>
     * Message contents
     * </pre>
     *
     * <code>repeated string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes(int index) {
      return message_.getByteString(index);
    }

    public static final int ADDON_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList addon_;
    /**
     * <pre>
     * Additional info used for some Packet types
     * </pre>
     *
     * <code>repeated string addon = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAddonList() {
      return addon_;
    }
    /**
     * <pre>
     * Additional info used for some Packet types
     * </pre>
     *
     * <code>repeated string addon = 4;</code>
     */
    public int getAddonCount() {
      return addon_.size();
    }
    /**
     * <pre>
     * Additional info used for some Packet types
     * </pre>
     *
     * <code>repeated string addon = 4;</code>
     */
    public java.lang.String getAddon(int index) {
      return addon_.get(index);
    }
    /**
     * <pre>
     * Additional info used for some Packet types
     * </pre>
     *
     * <code>repeated string addon = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAddonBytes(int index) {
      return addon_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUUIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uUID_);
      }
      if (type_ != protobuf.PacketProtos.Packet.Type.CONNECTION.getNumber()) {
        output.writeEnum(2, type_);
      }
      for (int i = 0; i < message_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_.getRaw(i));
      }
      for (int i = 0; i < addon_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, addon_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUUIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uUID_);
      }
      if (type_ != protobuf.PacketProtos.Packet.Type.CONNECTION.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < message_.size(); i++) {
          dataSize += computeStringSizeNoTag(message_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMessageList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < addon_.size(); i++) {
          dataSize += computeStringSizeNoTag(addon_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAddonList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.PacketProtos.Packet)) {
        return super.equals(obj);
      }
      protobuf.PacketProtos.Packet other = (protobuf.PacketProtos.Packet) obj;

      if (!getUUID()
          .equals(other.getUUID())) return false;
      if (type_ != other.type_) return false;
      if (!getMessageList()
          .equals(other.getMessageList())) return false;
      if (!getAddonList()
          .equals(other.getAddonList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUUID().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (getMessageCount() > 0) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageList().hashCode();
      }
      if (getAddonCount() > 0) {
        hash = (37 * hash) + ADDON_FIELD_NUMBER;
        hash = (53 * hash) + getAddonList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.PacketProtos.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.PacketProtos.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.PacketProtos.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.PacketProtos.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.PacketProtos.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.PacketProtos.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.PacketProtos.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.PacketProtos.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.PacketProtos.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.PacketProtos.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.PacketProtos.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.PacketProtos.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.PacketProtos.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Packet)
        protobuf.PacketProtos.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.PacketProtos.internal_static_protobuf_Packet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.PacketProtos.internal_static_protobuf_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.PacketProtos.Packet.class, protobuf.PacketProtos.Packet.Builder.class);
      }

      // Construct using protobuf.PacketProtos.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uUID_ = "";

        type_ = 0;

        message_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        addon_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.PacketProtos.internal_static_protobuf_Packet_descriptor;
      }

      @java.lang.Override
      public protobuf.PacketProtos.Packet getDefaultInstanceForType() {
        return protobuf.PacketProtos.Packet.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.PacketProtos.Packet build() {
        protobuf.PacketProtos.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.PacketProtos.Packet buildPartial() {
        protobuf.PacketProtos.Packet result = new protobuf.PacketProtos.Packet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.uUID_ = uUID_;
        result.type_ = type_;
        if (((bitField0_ & 0x00000004) != 0)) {
          message_ = message_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.message_ = message_;
        if (((bitField0_ & 0x00000008) != 0)) {
          addon_ = addon_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.addon_ = addon_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.PacketProtos.Packet) {
          return mergeFrom((protobuf.PacketProtos.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.PacketProtos.Packet other) {
        if (other == protobuf.PacketProtos.Packet.getDefaultInstance()) return this;
        if (!other.getUUID().isEmpty()) {
          uUID_ = other.uUID_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.message_.isEmpty()) {
          if (message_.isEmpty()) {
            message_ = other.message_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMessageIsMutable();
            message_.addAll(other.message_);
          }
          onChanged();
        }
        if (!other.addon_.isEmpty()) {
          if (addon_.isEmpty()) {
            addon_ = other.addon_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAddonIsMutable();
            addon_.addAll(other.addon_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.PacketProtos.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.PacketProtos.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uUID_ = "";
      /**
       * <pre>
       * UUID of client/server sending the message
       * Server username is SERVER
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public java.lang.String getUUID() {
        java.lang.Object ref = uUID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uUID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * UUID of client/server sending the message
       * Server username is SERVER
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUUIDBytes() {
        java.lang.Object ref = uUID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uUID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * UUID of client/server sending the message
       * Server username is SERVER
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public Builder setUUID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uUID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * UUID of client/server sending the message
       * Server username is SERVER
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public Builder clearUUID() {
        
        uUID_ = getDefaultInstance().getUUID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * UUID of client/server sending the message
       * Server username is SERVER
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public Builder setUUIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uUID_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.protobuf.Packet.Type type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.protobuf.Packet.Type type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.Packet.Type type = 2;</code>
       */
      public protobuf.PacketProtos.Packet.Type getType() {
        @SuppressWarnings("deprecation")
        protobuf.PacketProtos.Packet.Type result = protobuf.PacketProtos.Packet.Type.valueOf(type_);
        return result == null ? protobuf.PacketProtos.Packet.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.protobuf.Packet.Type type = 2;</code>
       */
      public Builder setType(protobuf.PacketProtos.Packet.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.Packet.Type type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList message_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMessageIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          message_ = new com.google.protobuf.LazyStringArrayList(message_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       * Message contents
       * </pre>
       *
       * <code>repeated string message = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMessageList() {
        return message_.getUnmodifiableView();
      }
      /**
       * <pre>
       * Message contents
       * </pre>
       *
       * <code>repeated string message = 3;</code>
       */
      public int getMessageCount() {
        return message_.size();
      }
      /**
       * <pre>
       * Message contents
       * </pre>
       *
       * <code>repeated string message = 3;</code>
       */
      public java.lang.String getMessage(int index) {
        return message_.get(index);
      }
      /**
       * <pre>
       * Message contents
       * </pre>
       *
       * <code>repeated string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes(int index) {
        return message_.getByteString(index);
      }
      /**
       * <pre>
       * Message contents
       * </pre>
       *
       * <code>repeated string message = 3;</code>
       */
      public Builder setMessage(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMessageIsMutable();
        message_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Message contents
       * </pre>
       *
       * <code>repeated string message = 3;</code>
       */
      public Builder addMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMessageIsMutable();
        message_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Message contents
       * </pre>
       *
       * <code>repeated string message = 3;</code>
       */
      public Builder addAllMessage(
          java.lang.Iterable<java.lang.String> values) {
        ensureMessageIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, message_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Message contents
       * </pre>
       *
       * <code>repeated string message = 3;</code>
       */
      public Builder clearMessage() {
        message_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Message contents
       * </pre>
       *
       * <code>repeated string message = 3;</code>
       */
      public Builder addMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMessageIsMutable();
        message_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList addon_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddonIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          addon_ = new com.google.protobuf.LazyStringArrayList(addon_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <pre>
       * Additional info used for some Packet types
       * </pre>
       *
       * <code>repeated string addon = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAddonList() {
        return addon_.getUnmodifiableView();
      }
      /**
       * <pre>
       * Additional info used for some Packet types
       * </pre>
       *
       * <code>repeated string addon = 4;</code>
       */
      public int getAddonCount() {
        return addon_.size();
      }
      /**
       * <pre>
       * Additional info used for some Packet types
       * </pre>
       *
       * <code>repeated string addon = 4;</code>
       */
      public java.lang.String getAddon(int index) {
        return addon_.get(index);
      }
      /**
       * <pre>
       * Additional info used for some Packet types
       * </pre>
       *
       * <code>repeated string addon = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAddonBytes(int index) {
        return addon_.getByteString(index);
      }
      /**
       * <pre>
       * Additional info used for some Packet types
       * </pre>
       *
       * <code>repeated string addon = 4;</code>
       */
      public Builder setAddon(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddonIsMutable();
        addon_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Additional info used for some Packet types
       * </pre>
       *
       * <code>repeated string addon = 4;</code>
       */
      public Builder addAddon(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddonIsMutable();
        addon_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Additional info used for some Packet types
       * </pre>
       *
       * <code>repeated string addon = 4;</code>
       */
      public Builder addAllAddon(
          java.lang.Iterable<java.lang.String> values) {
        ensureAddonIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, addon_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Additional info used for some Packet types
       * </pre>
       *
       * <code>repeated string addon = 4;</code>
       */
      public Builder clearAddon() {
        addon_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Additional info used for some Packet types
       * </pre>
       *
       * <code>repeated string addon = 4;</code>
       */
      public Builder addAddonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAddonIsMutable();
        addon_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Packet)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Packet)
    private static final protobuf.PacketProtos.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.PacketProtos.Packet();
    }

    public static protobuf.PacketProtos.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      @java.lang.Override
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.PacketProtos.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\010protobuf\"\346\001\n\006Packet\022\014\n\004" +
      "UUID\030\001 \001(\t\022#\n\004type\030\002 \001(\0162\025.protobuf.Pack" +
      "et.Type\022\017\n\007message\030\003 \003(\t\022\r\n\005addon\030\004 \003(\t\"" +
      "\210\001\n\004Type\022\016\n\nCONNECTION\020\000\022\t\n\005LOBBY\020\001\022\016\n\nS" +
      "TART_GAME\020\002\022\r\n\tPLAY_CARD\020\003\022\014\n\010BUY_CARD\020\004" +
      "\022\r\n\tGAIN_CARD\020\005\022\r\n\tDRAW_CARD\020\006\022\014\n\010END_TU" +
      "RN\020\007\022\014\n\010END_GAME\020\010B\016B\014PacketProtosb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Packet_descriptor,
        new java.lang.String[] { "UUID", "Type", "Message", "Addon", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
